export const BO = {
  "B/S": "/img/flags/norway.svg",
  "BS.": "/img/flags/norway.svg",
  "Cz.": "/img/flags/czech-republic.svg",
  "Fr.": "/img/flags/switzerland.svg",
  "Gr.": "/img/flags/greece.svg",
  "KS.": "/img/flags/norway.svg",
  "Mo.": "/img/flags/monaco.svg",
  "Ne.": "/img/flags/netherlands.svg",
  "SD.": "/img/flags/switzerland.svg",
  "Sp.": "/img/flags/norway.svg",
  "SP.": "/img/flags/sweden.svg",
  "Sw.": "/img/flags/switzerland.svg",
  "Ti.": "/img/flags/finland.svg",
  "Va.": "/img/flags/finland.svg",
  ASV: "/img/flags/austria.svg",
  AUT: "/img/flags/austria.svg",
  BLR: "/img/flags/belarus.svg",
  BoS: "/img/flags/sweden.svg",
  BSHK: "/img/flags/sweden.svg",
  CAN: "/img/flags/canada.svg",
  Czech: "/img/flags/czech-republic.svg",
  ES: "/img/flags/spain.svg",
  FIN: "/img/flags/finland.svg",
  FRA: "/img/flags/france.svg",
  Fribourg: "/img/flags/switzerland.svg",
  GAK: "/img/flags/austria.svg",
  Greece: "/img/flags/greece.svg",
  IT: "/img/flags/italy.svg",
  JSS: "/img/flags/sweden.svg",
  KSTK: "/img/flags/norway.svg",
  LUK: "/img/flags/denmark.svg",
  MKK: "/img/flags/sweden.svg",
  Monaco: "/img/flags/monaco.svg",
  Netherland: "/img/flags/netherlands.svg",
  PL: "/img/flags/republic-of-poland.svg",
  ROU: "/img/flags/romania.svg",
  SDG: "/img/flags/switzerland.svg",
  SDRD: "/img/flags/switzerland.svg",
  SPIF: "/img/flags/sweden.svg",
  Spinn: "/img/flags/norway.svg",
  SSC: "/img/flags/norway.svg",
  Swiss: "/img/flags/switzerland.svg",
  Tiirat: "/img/flags/finland.svg",
  UKR: "/img/flags/ukraine.svg",
  VanDi: "/img/flags/finland.svg",
  VSS: "/img/flags/sweden.svg"
};
export const EJC2017 = {
  "LEN TDC": "/img/lenflag.png",
  "TS&": "/img/trondheim.png",
  AUT: "/img/flags/austria.svg",
  BaS: "/img/Bas.png",
  BGR: "/img/flags/bulgaria.svg",
  BLR: "/img/flags/belarus.svg",
  BSt: "/img/BStKlogo.svg",
  BUL: "/img/flags/bulgaria.svg",
  CRO: "/img/flags/croatia.svg",
  CZE: "/img/flags/czech-republic.svg",
  DEN: "/img/flags/denmark.svg",
  EGY: "/img/flags/egypt.svg",
  ESP: "/img/flags/spain.svg",
  FIN: "/img/flags/finland.svg",
  FRA: "/img/flags/france.svg",
  GBR: "/img/flags/united-kingdom.svg",
  GEO: "/img/flags/georgia.svg",
  GER: "/img/flags/germany.svg",
  GRE: "/img/flags/greece.svg",
  HUN: "/img/flags/hungary.svg",
  ITA: "/img/flags/italy.svg",
  Kle: "/img/Kle.png",
  KST: "/img/kristiansand.png",
  KUW: "/img/flags/kuwait.svg",
  LTU: "/img/flags/lithuania.svg",
  NED: "/img/flags/netherlands.svg",
  NOR: "/img/flags/norway.svg",
  Osl: "/img/Osl.png",
  POL: "/img/flags/republic-of-poland.svg",
  PUR: "/img/flags/puerto-rico.svg",
  PSK: "/img/pingvin.jpg",
  ROU: "/img/flags/romania.svg",
  rs: "/img/randaberg.png",
  RS: "/img/randaberg.png",
  RUS: "/img/flags/russia.svg",
  Spi: "/img/spinn.png",
  SRB: "/img/flags/serbia.svg",
  SSC: "/img/ssc.png",
  SUI: "/img/flags/switzerland.svg",
  SWE: "/img/flags/sweden.svg",
  TUR: "/img/flags/turkey.svg",
  RSA: "/img/flags/south-africa.svg",
  AUS: "/img/flags/australia.svg",
  UKR: "/img/flags/ukraine.svg"
};

export const ddd = {
  DDD: "/img/dods.svg"
};

export default EJC2017;
